### ISSUE TITLE
Comments on the 2.2-01 release

### ISSUE THREAD

**Issue by codeviolet** [AVsitter/AVsitter#10]
Just a few comments as I was not sure where else better to put them...

* I have updated all the scripts with those from the [2.2-01.zip](https://github.com/AVsitter/AVsitter/releases/tag/2.2-01) and placed the 2.2-01 box in the inworld updater. All scripts that were updated have had their description changed to "2.2-01".

* I did not update the main Lockguard script as it should not be optimized. This script is intended for the user to edit thus the optimization is not needed. @sei-lisa are you able to specify to exclude the Lockguard script from optimization in future (but still have it include the script in the zip), in the makefile you are working on?

* The [Updater scripts](/AVsitter/AVsitter/tree/master/AVsitter2/Utilities/Updater) were not intended to be part of the releases, unless there is a reason for them to be. Can we specify to exclude them from the zip in the makefile?

* All scripts in the release seem to work well in SL. However, I thought it worth noting that my testing was minimal and I do not currently have a rigorous set of test steps in place. Given my time constraints, I can not plan to test releases as thoroughly as may be needed before packaging in future (if at all). Therefore, a test procedure that is carried out before release may be an idea. For several months I used a test procedure similar to [LL's set of test steps](http://wiki.secondlife.com/wiki/Category:Test_Scripts). I abandoned using a test procedure as I became more confident in the changes I was making between releases, but it was very useful until then. Maybe it's too time-consuming to create a written procedure, but my thoughts are more along the lines of how best to ensure that the releases actually work. Just thoughts.

**Comment by Sei-Lisa** [comment]
Thanks for your notes and for the release. Yes, there's a provision for scripts that need to be packed but not optimized in the Makefile. The updater scripts can simply be removed from the Makefile. I didn't go over each script, I merely updated them all, sorry. I'll upload a new zipfile. Thanks for the heads-up.

I've kept the branch I used for #8 open [in my repository](https://github.com/Sei-Lisa/AVsitter/tree/sei-release-2.2-01/AVsitter2) and I'm pushing changes there, so I can cherry-pick and amend commits later from it, but it can be used as a sneak peek of the Makefile and the rest of changes that are to come.

A unit testing procedure would be awesome to have, and I'm willing to follow one to ensure the integrity of releases. I would have a hard time figuring out how to perform tests for the relevant code sections. I'm confused by the "test procedure" vs. "written procedure". Do you mean your test procedure was not in written form?

**Comment by codeviolet** [comment]
Sorry I could have been clearer about release testing in my message. In all cases I meant a "written test procedure" to be manually performed by someone before a release, like [LL's set of manual test scripts](http://wiki.secondlife.com/wiki/Category:Test_Scripts). Automated 'unit testing' would be another idea, but it is not what I meant.

What I meant to say there at the end was that creating a "written test procedure" is just an idea, that may or may not be worth doing. I had found a written test procedure useful early on for uncovering bugs before each release but abandoned it once the scripts were more stable, and especially once the set of example items matured to cover a wide spectrum of use cases. Testing the examples before release became a better way, for me, of achieving the a kind of quality assurance that a written test procedure also aims to achieve.

The overall concern I mean to raise about testing is that with the new open-source development work flow, how will the developers ensure that releases are bug free? The question of release testing is not something that needs an answer now I think, but something to consider.

At the moment the only release testing that I am aware of is my testing that the example objects work as intended with the release, before I package it. I don't want to rely as much on this in future so I suggest a more formal description of testing should probably be developed and agreed to by developers at some stage.

I do like your notion that GitHub releases could follow some of the [Semantic Versioning](http://semver.org) principles of "beta" and "rc", and this would allow a chance for scripts to undergo more testing before inworld release. Whether there should be any formal testing procedure is open to question, and obviously not urgent :)

**Comment by Sei-Lisa** [comment]
If you have a written test procedure we could perhaps use as a basis to modernize it, maybe it can be included in the repository?

Or do you think that testing that the examples do what they are supposed to do should suffice?

I'm willing to do the testing before issuing every GitHub+MP release. I just need to be reasonably sure that the testing is complete enough as to cover most use cases as to reveal the most prominent bugs, should any be present. If there are subtler bugs that only appear in marginal cases, that's a bit beyond the testing that is reasonable to do, as there are lots of marginal cases.

I don't think that automated unit testing is viable without something like a "SL emulator". I've been thinking of writing one such tool, but it's certainly not in the short-term plans.

**Comment by codeviolet** [comment]
I don't have my old written test procedure easily on hand, although it was useful for me to have one early on. I will see about writing a new one in tandem with testing #16 in OpenSim. Testing that the examples do what they are supposed to do is better approach than following a purely written test procedure so my new written test procedure may reference the examples. I will see how I go.

Regarding the examples:

* The current AVsitter2 examples are listed at https://avsitter.github.io/avsitter2_examples.html

* Although most basic use cases are covered by the examples, there is quite some room for improvement in the examples if they are to cover every possible use case. They are mostly all intended to test or demonstrate specific features. However, none of the examples have a very complex menu structure.

* The examples were always a balance between testing and providing users with example objects that were easy to digest (they are not purely designed for testing, but also for basic demonstration of features).

* The current examples require animations which can't be given out fullperm due to their creators TOS.

* Although they are included in the MP distribution, I can send a COPY-OK version of the current examples to anyone who requests them in SL.

* Perhaps an upgrade of the examples could be a future project for a contributor.

**Comment by Sei-Lisa** [comment]
Is there anything pending to do or answer here?

**Comment by codeviolet** [comment]
Now that the example items are tested by me to be working in OpenSim I don't think a written test procedure is urgent. Testing the examples is fairly straight-forward and provides a good indication whether the various aspects of the scripts are working. I think we can close this issue.

**Comment by Sei-Lisa** [comment]
Thanks, closing then. I'd still appreciate a test procedure for the examples. The names and hovering texts aren't enough indication for me to determine what to test yet. I'm not experienced in so many setups.

Also, #35 has revealed a problem that no example currently covers, so perhaps AVcontrol example 12 needs ONTOUCH ASK.
