### ISSUE TITLE
bug when i want to make an animation.

### ISSUE THREAD

**Issue by RCorentin** [AVsitter/AVsitter#100]
The situation : 
When i click on a object with the AVsitter script in it ([AV]adjuster, [AV]helper(the object), [AV]sitA, [AV]sitB, AVpos and 2 animation), the menu appears. Then i click [ADJUST], then [HELPER] but when i click on [NEW] the menu just close.
PS: i'm not on Second Life but in a Open Sim. (Of course I use the AVSitter for Open Sim)
Do you know what goes wrong ?

![2018-05-18_16-03-18](https://user-images.githubusercontent.com/24584388/40239032-2b2a62bc-5ab5-11e8-84f4-f923178dfb9d.gif)
![firestormos-releasex64_2018-05-18_15-59-42](https://user-images.githubusercontent.com/24584388/40239059-40328ab8-5ab5-11e8-922c-f8c3678be1d2.png)

**Comment by Sei-Lisa** [comment]
It's working for me. I could only reproduce your issue by unchecking the Running checkbox for [AV]adjuster, which makes me think that yours is either the wrong script, or not running.

Please check that your [AV]adjuster is correctly imported and running. Open it and verify that the header of the script includes this text:

```
 * [AV]adjuster - Create a setup and an AVpos notecard from scratch
```

If you're not using the latest version (2.2-03.01), please grab it first.

**Comment by RCorentin** [comment]
Hi, thanks for your answer. you will laugh but I just forget to put the code in the [AV]Adjuster file.
Now it's work perfectly !

**Comment by Sei-Lisa** [comment]
No worries, thanks for reporting back!
