### ISSUE TITLE
Is there a converter for MPS system to AVSitter?

### ISSUE THREAD

**Issue by avelluna** [AVsitter/AVsitter#101]
Has there been any development for a converter for MPS Sit system to AVSitter?

**Comment by Sei-Lisa** [comment]
Well, I wrote a very simple one some time ago. It only converts pose names and positions/rotations, not menus or other features. I planned to expand it to something more complete, but I need to study the format of MPS notecards in more detail and I never got to that. Anyway, given that MPS uses one different prim per sitter, it's unlikely that this script will ever do more than it does now.

I've uploaded it here: https://github.com/Sei-Lisa/AVsitter/blob/sei-mps-converter/AVsitter2/Utilities/MPS-converter.lsl

**Comment by avelluna** [comment]
Thank you so much!
