### ISSUE TITLE
New Release not working in Kitely

### ISSUE THREAD

**Issue by BraylaSana** [AVsitter/AVsitter#107]
2.2 works fine, but I downloaded the OpenSim-AVsitter2.2-03.01 release so I could try to use props.  When I try to compile the scripts, I get this error:

ERROR: C:\ProgramFiles\FirestormOS-Release64\[AV]sitA (87): error: universal character name specifies an invalid character: \u007F

**Comment by BraylaSana** [comment]
All scripts that have the line

`string SEP = "\u007F";`

generate this error.

**Comment by Sei-Lisa** [comment]
Uh, that has worked for me in past. They must have changed something. I'll test. Thanks for reporting.

**Comment by BraylaSana** [comment]
Here are my specs:
`Firestorm 5.1.7 (55786) Jul 13 2018 22:34:51 (64bit) (Firestorm-Releasex64) with OpenSimulator support
Release Notes

You are at 429.0, 43.6, 29.2 in Brayla Sana Gallery located at ec2-18-144-1-122.us-west-1.compute.amazonaws.com (18.144.1.122:9016)
SLURL: hop://grid.kitely.com:8002/Brayla%20Sana%20Gallery/429/44/29
(global coordinates 3,047,850.0, 2,066,480.0, 29.2)
OpenSim 0.8.2.1 Post_Fixes        (Unix/Mono)
Error fetching server release notes URL.

CPU: AMD FX(tm)-8320 Eight-Core Processor            (3516.07 MHz)
Memory: 16342 MB
OS Version: Microsoft Windows 10 64-bit (Build 17134)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce GTX 960/PCIe/SSE2

Windows Graphics Driver Version: 24.21.13.9836
OpenGL Version: 4.6.0 NVIDIA 398.36

RestrainedLove API: (disabled)
libcurl Version: libcurl/7.54.1 OpenSSL/1.0.2l zlib/1.2.8 nghttp2/1.25.0
J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 1.10.05
Dullahan: 1.1.1080 / CEF: 3.3325.1750.gaabe4c4 / Chromium: 65.0.3325.146
LibVLC Version: 2.2.8
Voice Server Version: Vivox 4.6.0017.22050

Settings mode: Hybrid
Viewer Skin: Metaharper Modern (CoolOcean)
Window size: 1920x1080 px
Font Used: Deja Vu (96 dpi)
Font Size Adjustment: 0 pt
UI Scaling: 1
Draw distance: 128 m
Bandwidth: 1250 kbit/s
LOD factor: 2
Render quality: High-Ultra (6/7)
Advanced Lighting Model: Yes
Texture memory: 2048 MB (1)
VFS (cache) creation time (UTC): 2018-7-23T21:0:1 
Built with MSVC version 1800
Packets Lost: 1/2,565 (0.0%)
October 05 2018 19:52:23 SLT`

**Comment by Sei-Lisa** [comment]
OK, I see what's going on. The error comes from Firestorm's preprocessor, not from the sim. Disable the preprocessor prior to compiling the scripts and they should compile fine.

**Comment by Sei-Lisa** [comment]
I've found a workaround for that problem, and I'm going to send a patch for it.

Replace the `\u007F` with `\x7F` and it will work no matter if the preprocessor is active.

**Comment by Sei-Lisa** [comment]
Addressed in https://github.com/AVsitter/AVsitter/pull/108 - thanks again for reporting.

**Comment by BraylaSana** [comment]
Thanks for the help.
