### ISSUE TITLE
Avatar Removed from Furniture Ban List Still Unable to Sit

### ISSUE THREAD

**Issue by ohhmye** [AVsitter/AVsitter#123]
I put together a ban list for furniture. An avatar on the list is unseated when it sits. But when I remove the avatar from the list, the avatar still cannot sit. The avatar can't sit even after a script reset. The script must be deleted from the furniture's inventory to allow the avatar to sit.

I tried the same using a touch event on a prim. Avatars not on its ban list are greeted. Avatars on the list are not greeted. This works as it should. Once the avatar is removed from the list, it's given a greeting.

There's [reference to this issue on the AVsitter support website](https://avsitter.com/qa/1278/using-scripted-unsit-command-is-not-releasing-from-controls.html). Seemingly resolved by a workaround, the problem isn't actually addressed.

I've sent @Sei-Lisa a folder named #ListTest with test objects and scripts.

Viewer: Firestorm 6.3.2 (58052) Sep 27 2019 22:41:52 (64bit)
Scripts run on parcel: 85-95%

To duplicate:
-Add list of avatars not allowed to sit on furniture
-Have avatar on list sit and be unseated
-Remove avatar from list
-Have avatar attempt to sit on furniture

**Comment by Sei-Lisa** [comment]
Thanks for the report. From what I can see in your script, the script itself has a problem. The touch version and the unsit version check the list differently, and the unsit version does not do it correctly.
