### ISSUE TITLE
1-char animation names?

### ISSUE THREAD

**Issue by elizaveta-markova** [AVsitter/AVsitter#133]
Is there a bug affecting AvPos when the animation name has only one character? I have no-mod anims stupidly named "M" and "F". It looks like if I use them, not only that line but also subsequent lines of AvPos are not parsed correctly.

**Comment by Sei-Lisa** [comment]
I've had no problems when testing poses using animations named `M` and `F`. Could you please elaborate on the setup?

**Comment by elizaveta-markova** [comment]
I am unable to replicate the problem. Thanks for checking, and please accept my apology.
