### ISSUE TITLE
CUSTOM_TEXT

### ISSUE THREAD

**Issue by wEPac** [AVsitter/AVsitter#135]
hello, thank you for all the work you already did, the code is clean now and pretty nice to read. May I suggest to allow '\t' for CUSTOM_TEXT ?

`if (command == "TEXT")`
`{`
`    CUSTOM_TEXT = llDumpList2String(llParseStringKeepNulls(part0, ["\\n"], []), "\n");`
`    CUSTOM_TEXT = llDumpList2String(llParseStringKeepNulls(CUSTOM_TEXT, ["\\t"], []), "\t");`
`    return;`
`}`

**Comment by Sei-Lisa** [comment]
Thanks for the suggestion. In LSL, "\t" always translates to 4 spaces at compile time, so I don't see much value in this. Actual tabs (e.g. llUnescapeURL("%09")) don't really work in the viewer. I don't think this feature is worth the extra code and memory usage. Note that this string replacement technique is fast, but it generates a lot of garbage in a very short time that can drain the available memory quickly before there's a chance to recover - that happened to me in another project which had multiple such substitutions in sequence.

Please close if you agree.

**Comment by wEPac** [comment]
I fully agree, the most important is to save memory for further and more important usage. Using \t beside 4 empty spaces in the notecard will not be enough usefull for the code line we have to add. For the fun I would add (CUSTOM_TEXT="") + CUSTOM_TEXT, the good old hint that wont help our poor 64kB ;) Thanks a lot for the work you already did, I mostly enjoyed the indentation of the code :)
