### ISSUE TITLE
AVSitter2 AVhelper doesnt work properly

### ISSUE THREAD

**Issue by Ysiralos** [AVsitter/AVsitter#136]
I downloaded AVsitter2 using https://github.com/AVsitter/AVsitter/blob/master/AVsitter2/IMPORT_GUIDE.md
and have followed instructions to install properly and save to my SL using Firestorm
Using the following instructions on  https://avsitter.github.io/avsitter2_home , and when attempting to insert an
 animation into a prim i get errors with the program as shown on the attached screenshots.  
![Screenshot_2](https://user-images.githubusercontent.com/78396456/106547615-8a8c5480-64db-11eb-89d9-5bc7bfd92344.png)
![Screenshot_3](https://user-images.githubusercontent.com/78396456/106547625-8e1fdb80-64db-11eb-9b4b-6ea33e6b7181.png)
The helper button doesn't come up so I can continue working.

Please advise, Thank you! 
ysiralos@hotmail.com
Solar

**Comment by wEPac** [comment]
There is something wrong in your configuration, you directly pasted the script helper into the content, You must paste this script into an empty prim, then paste this prim into your seat, where you have the scripts Ajuster, sitA ... like the instructions are well explaining ;)

**Comment by Sei-Lisa** [comment]
Indeed, but I'd say "drop" instead of "paste". Take good note of step 7 in the Import Guide, and drop the `[AV]helper` **object** you prepared into your object. Do **not** drop the `[AV]helperscript` **script**.

**Comment by Ysiralos** [comment]
Wow! I was completely ignoring that step of dropping the helperscript into a prim and then adding that prim into the piece itself!!
100% Support from you two!
Thanks so much! You totally made my week!
*****
