### ISSUE TITLE
looking for more free bytes...

### ISSUE THREAD

**Issue by wEPac** [AVsitter/AVsitter#137]
Hello, as I know our 64k are always short, reading the code I often see these...
`if (num == -1) ...`
and 
`if (num != -1) ...`

that could easy be replaced by
`if (!~num) ...`
and
`if (~num) ...`

I dont know if that can work in Open Sim, but it should like a pure bolean operation.

Have a good day.

**Comment by Sei-Lisa** [comment]
Thanks for your concern. The scripts in the distribution are processed by an optimizer that takes care of that and many other optimizations. Please consult https://github.com/AVsitter/AVsitter/blob/master/AVsitter2/BUILD_GUIDE.md if you want to build an optimized release from the repository sources.

OpenSim does not have a memory limit that I'm aware of, therefore these optimizations are not applied to the OpenSim scripts. But OpenSim has a few differences in behaviour with LSL, that are taken care by special markings in the AVsitter scripts, when processed by the build system.
