### ISSUE TITLE
Suggestion: New notecard command to change the object name on the menu

### ISSUE THREAD

**Issue by AurynBeorn** [AVsitter/AVsitter#138]
Currently, the AVsitter menu shows the object name when opening the menu.
Is it possible to add a notecard command that allows to change this?

For example, if there's this line on AVpos, at the top (after ADJUST or wherever):

OBJECTNAME My Object Name

then we will see the menu text begin by:

Auryn Beorn's 'My Object Name'

and if this OBJECTNAME line doesn't exist, then we get the regular:

Auryn Beorn's 'the_object_name'

The reason behind this suggestion is that now my Texture Change script admits the t; blocks in the name when necessary, and in doing so, they appear on the menu text. The idea is to avoid this. Of course, the new command can be named OBJECTNAME or how it's deemed necessary.

**Comment by Sei-Lisa** [comment]
That's something LL adds automatically to dialogs, and we have no control over it, sorry.

**Comment by AurynBeorn** [comment]
Nevermind, it can't be changed...
