### ISSUE TITLE
Ability to ask user if they would like the auto attaching props y/n.... 

### ISSUE THREAD

**Issue by Dictatorshop** [AVsitter/AVsitter#15]
This is wishlist nice to have stuff, but if you are taking ideas here is one that is high in my wishlist.

I have been setting all my stuff with cuffs, coffee, popcorn and whatnot included.  It would be cool if a user could choose once when they sit whether they want  the items to wear or not (ie if they have their own beloved cuffs that they wear everywhere all the time causing lag wherever they go, lol).   Or alternately if it could detect attachments at those points and ask or just not wear.  

Would this sort of advance selection allow auto attaching without experience enabled by chance?  Given that it may end up being weird with the "avsitter experience" being open source code now and none of us having the right to create for the avsitter experience - might this be a way around that little conundrum?

**Comment by Dictatorshop** [comment]
I am not familiar with this GitHub system, is there a certain way to categorize "hey here's an idea" suggestions?  This isnt really an issue... Does it go under requests or?  Let me know please, I dont want to be making annoying suggestions :-)

**Comment by Sei-Lisa** [comment]
Labels can only be added by project members. The "enhancement" label is for enhancement proposals like this one.

I'll think more about your proposal, and other people are invited to express their opinion as well.

**Comment by Sei-Lisa** [comment]
I'm not sure how you have in mind this feature to work.

If it's per prop, then you can simply recompile \[AV\]object disabling the experience, and put the experience-disabled script into the props that you want to ask the user always.

If that doesn't seem like an appropriate solution, could you please explain how you think it should work?

**Comment by Dictatorshop** [comment]
Well,  honestly I am not sure how the attach permissions work for SL these days...  The experience thing was just an add-on thought to my main issue.  The main issue being:

I have my furniture set up to auto attach needed items, cuffs, dildos and spankers for example.  It came to my attention that while *most* of my customers appreciate not having to dig in inventory for items like this and risk interrupting their play - but there are others who prefer to use their own items and find the auto attaching annoying in some cases.  Those people being ones who have their own cuffs that they prefer, or a favored whip/spanker attachment.

My first thought and something I had discussed once with Code Violet was to be able to have a script check if there was already something attached to the spot my attachment would want to attach to ( at wrists/ankles or right hand for example) and simply not attach the items, or else pop up a dialog box asking if the user wanted this item to add the items (even with experience turned on).  So default behavior, if no attachment at these points then add automatically, else ask.  

- - - - (the not critical musings here) - - - -

The add-on thought I was having was "well if you are potentially going to be asking the user if they want your attachments.... could you just ask them when they sit down if they want the auto attaching or not, could you bypass the need for the experience by simply getting it out of the way "on sit" as one single yes or no."

The add-on thought only really works if it is possible to ask once and have user giving permission for multiple items to attach as ONE permission given or not without the experience needed.  If the answer to that is no (and each prop will ask independently), then forget this whole second part here as being moot.  I am fine using the experience if it is going to continue to work for us even though the scripts are going open source.  I was mostly just curious if this was possible without experience and without each prop having to ask.  Having each cuff asking and the user having to click four times to wear them is no good in my book, so whichever way we have to keep *that* from happening is fine with me.

**Comment by Sei-Lisa** [comment]
To attach multiple prims without experience permissions, each prim has to ask permission individually, there's no way around that as that's how SL works.

Unfortunately the scripts can't distinguish if the user is wearing a cuff or a bangle or a bracelet.

There's also the detail that attachments can't know their attachment points: SL remembers them internally and AVsitter just attaches them to their default att.point. You'd need to define the attachment points somehow, in addition to the rest of prop data, during setup, if you want the script to be able to determine whether there's something attached there already.

Coordinating all attachments to find whether there's something in their corresponding attachment point would be quite difficult too.

Adding a dialog where there's currently none can also annoy other users.

All things considered, I don't think it's likely that this feature will be implemented. Too much code for too little gain, and then it would work only in case the experience is enabled, and benefit a reduced number of people.

**Comment by Sei-Lisa** [comment]
Sorry, I was wrong about the attachment point; there is an attachment point option already present. The rest of arguments hold, though.

**Comment by Dictatorshop** [comment]
I see your point.  If each thing has to ask anyway then the rest is just... meh.  I may be able to just work out a little extra script to go with the existing system or something just for my own amusement.  I'd say ignore this request.
