### ISSUE TITLE
AVsitter2: no menu when i sit

### ISSUE THREAD

**Issue by notnot** [AVsitter/AVsitter#19]
I followed the AVsitter2 documentation to make a simple sitter. Sadly i don't see a menu when i sit on it. All i see are 'Object touched' messages in local chat (4 for each touch). I am working with the latest .lsl code i got from here. Any clues?

**Comment by Sei-Lisa** [comment]
Hello, it looks like you haven't saved the scripts properly. My advice is to join the "Unofficial AVsitter Support Group" for help, because by holding a conversation in this issue tracker, it will take much longer to track down the problem and get it solved.

**Comment by notnot** [comment]
You were right, so stupid of me! I forgot to save after pasting, so the
scripts were still running the default code... Thanks!

**Comment by Sei-Lisa** [comment]
Glad you got it sorted out!
