### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by buildersbrewery** [AVsitter/AVsitter#2]
Github will show any `README.md` file of the current folder you are viewing as a rendered HTML section below the list of files and subfolders.

So, maybe renaming the reference in the `./AVSitter2` subfolder to `README.md` would make sense?

---

Also in that exact file you can highlight the code as LSL using:

    ```lsl
    // bla bla bla
    ```

within the markdown code sections with the `lsl` extension.

---

Also the main docs repo is scary for beginners who'd want to contribute, if I may say.

Github supports having the documentation in a `./docs` subfolder in the root of the master branch. See <https://github.com/AVsitter/AVsitter/settings> and the `Github Pages` section there. It would make sense to have the source and it's docs in the same repo and branch to ease parallel development and tagging.
I have had good experiences using a minimal docs setup with <https://github.com/QingWei-Li/docsify>.

Alternatively I can recommend keeping the docs in a subfolder (different from `./docs`) and generating them for every release using `Madoko`:

* <https://madoko.net/editor.html>
  * <http://madoko.org/reference.html>
  * <http://www.madoko.org/reference.pdf>

to put them in the other folders with the source where it would make sense.

**Comment by codeviolet** [comment]
Thank you for these suggestions. I can see that keeping the documentation in the same repository may ease parallel development and have the advantage of the docs being snapshotted along with releases.

Correct me if you know I'm wrong but I believe it would be possible to move the entire documentation repo to the ```/docs``` folder (or a branch called ```gh-pages```) and keep the current [Jekyll](https://jekyllrb.com/docs/github-pages/) theme which generates avsitter.github.io. That theme was chosen as it has a lot of similarity to the layout users are familiar with from the old website, however it can change in future. 

I feel there are some advantages to keeping the repositories separate such as separate Issues for users who need help with docs, versus script Issues, but if it will be advantageous to move the documentation to ```/docs``` then we should do so at some stage.

I'll leave this issue open for now for future discussion about this.

**Comment by buildersbrewery** [comment]
If you move the docs to the `./docs` subfolder of the root of the `master` branch here, you:

* can keep the current Jekyll theme.
* need to redirect `https://avsitter.github.io` to `https://avsitter.github.io/avsitter`

---

You could use the `gh-pages` branch, too. I'd suggest the above instead, though.

**Comment by Sei-Lisa** [comment]
I don't like the idea of mixing the documentation commit history with the project's. People working on documentation will probably be different most of the time from those working on the code. I'm all for keeping them separated, even for separating AVsitter1 to its own repo if it's not a lot of effort, but that change comes with drawbacks.

For novices, I don't see any advantage in having the docs hidden one level deeper within the main repo.

Having to add redirects is an additional drawback. The shorter the URLs are, the easier they are to handle.
