### ISSUE TITLE
Web dump not working when there's more than 1 chunk

### ISSUE THREAD

**Issue by sadie1757** [AVsitter/AVsitter#25]
Gotta love having no support here.. Who knows if anyone is even checking this.  Just to be clear "WE ARE ALL HAVING A PROBLEM WITH AVSITTER!! "
no dump feature is available Error message "Data was incomplete, please try again.

This feature is new and experimental - you're welcome to report any issues."

**Comment by Sei-Lisa** [comment]
It will be fixed as soon as it can be looked into. In the meantime, please use the chat dump instead.
