### ISSUE TITLE
Can't teleport due to  avsitter experience

### ISSUE THREAD

**Issue by sadie1757** [AVsitter/AVsitter#26]
Check out the attachment.. what the heck is this about?
![avsitter experience access](https://user-images.githubusercontent.com/31411507/29778774-6edb6886-8bde-11e7-9873-2b3cda1b4fc8.PNG)

**Comment by Sei-Lisa** [comment]
No idea, but this does not appear to be a bug in AVsitter.

**Comment by codeviolet** [comment]
Not sure, but perhaps this is the result of the experience being added to the wrong place by the land owner.

The [AVsitter experience](https://avsitter.github.io/avsitter2_prop.html#experience-keys) should be enabled at the Estate or Parcel level by adding it to the ‘Allowed Experiences’ list. It should NOT be added under "Key Experiences".

![experiences](https://user-images.githubusercontent.com/12992687/29800836-835288e0-8caf-11e7-81fb-ca24111b42b9.jpg)
