### ISSUE TITLE
Opensim. [AV]sitA: No handler registered for LLSD Resquests

### ISSUE THREAD

**Issue by Anthonyghub** [AVsitter/AVsitter#39]
When i try to save as script the file [AV]sitA in Opensim i get the following error: ''impossible to import the file d4d90179-b7b6-5dcb-4402-611805d145a1 due the following reason: No handler registered for LLSD Resquests . retry later''

**Comment by Sei-Lisa** [comment]
Since it's a problem saving the script, and not running it, this doesn't look like an AVsitter problem, but more like a sim problem.

Have you retried later as the error message suggests?

Have you tried in a different sim?

What is the version of the sim you've tried on? You can check in Help > About.

**Comment by Anthonyghub** [comment]
The script [AV]sitA isn't working neither while its into the content of the object and it won't load. Meanwhile [AV]sitB works correctly. I have tried later and in other sims but nothing. It's saying the error No handler registered for LLSD Resquests

**Comment by Sei-Lisa** [comment]
I've tried saving in inventory and it worked; I tried saving in the object and it worked. Could it be a problem with your viewer or your connection?

Are you using the .oss scripts?

What's your sim version again?

**Comment by Anthonyghub** [comment]
Try to create a new prim, then create a new script inside and paste the content of [AV]sitA.oss ; when you save the script it gives the error message from Firestorm viewer No handler registered for LLSD Resquests . I'm using .oss script. Current simulator: OpenSim 0.9.1.0 Dev  OSgrid 0.9.1.0 (Dev)  396ab14: 2017-08-25 (Win/.NET) I paste you the screenshot of the error
![977286b13855729eb00b75bd5a9860cb](https://user-images.githubusercontent.com/26225591/30233954-71dabedc-94f9-11e7-82ee-2fd53026e8cc.png)
There aren't syntax errors but there is this error from Firestorm viewer: i have uploaded the screenshot
I'm using Firestorm x64 5.0.1.52150

**Comment by Sei-Lisa** [comment]
I did that and had no problems with FS 5.0.3 in OSgrid (Sandbox Plaza II), same sim version.

**Comment by Sei-Lisa** [comment]
I have Linux, though. Might it be a problem with copy/paste in your OS?

**Comment by Anthonyghub** [comment]
i run windows. My firestorm is Firestorm x64 5.0.1.52150. Maybe some issue with that version? I paste correctly the content of the script. What about the error window No handler registered for LLSD Resquests ?

**Comment by Anthonyghub** [comment]
I have opened the [AV]sitA.oss with Notepad then i pasted the content as new script firestorm directly inside a cube

**Comment by Sei-Lisa** [comment]
> What about the error window No handler registered for LLSD Resquests ?

That error comes directly from OpenSim. See line 1165 in https://github.com/opensim/opensim/blob/3940a4dbc7ffb4eab319ea9c2f1f787ddeee65e8/OpenSim/Framework/Servers/HttpServer/BaseHttpServer.cs#L1165

> I have opened the [AV]sitA.oss with Notepad then i pasted the content as new script firestorm directly inside a cube

I suggest you to open it with `clip.exe`, which copies the content of the argument to the clipboard, and see if that works.

For that, you can use a command interpreter, and type: `clip "\path\to\[AV]sitA.oss"`

**Comment by Anthonyghub** [comment]
I have tried again in osgrid sandbox plaza but scripts seem to not work correctly. I have found your name and in Osgrid and added Lisa; so we can make tests together. Thanks

**Comment by Sei-Lisa** [comment]
I'm not Lisa in OSgrid, and I'm not Sei Lisa either, so whoever you added is not me :)

Can you please try with these scripts? https://github.com/AVsitter/AVsitter/files/1290792/AVsitter2-oss.zip

**Comment by Anthonyghub** [comment]
Hello Lisa i have created new script into a prim rezzed on the ground and pasted the content of [AV]sitA.oss but i receive the same error message 
![errore](https://user-images.githubusercontent.com/26225591/30272885-db7bc332-96f6-11e7-8d6b-9df92e02b828.png)

**Comment by Sei-Lisa** [comment]
I'm running out of ideas.

Have you tried the `clip.exe` method I suggested above?

If not, I suggest you to try that next.

If that does not work, try with `write.exe`: open a command interpreter and type `write`, and use that to open the script and copy/paste from there.

My last suggestion is to use the external editor option of Firestorm.

**Comment by Anthonyghub** [comment]
I have tried all methods but i always receive the error as above

**Comment by Sei-Lisa** [comment]
I can't reproduce this. Every time I try, the script saves without problems.

I made a mistake with `clip`. You need to use a "less than" symbol like this:

`clip < "\path\to\[AV]sitA.oss"`

Try that. If it doesn't work either, I suggest you report this problem here: http://opensimulator.org/mantis/

**Comment by Anthonyghub** [comment]
Hi Lisa! could you send me a copy of AVsitter scripts in Osgrid inside a prim please? My name on Osgrid is Casanova Wild . Thank you so much

**Comment by Anthonyghub** [comment]
Hello Lisa! I have tried to save with another viewer different from Firestorm and it seems that now scripts are working! Thanks! I also need the AVsitter utilities for opensim: Anim-perm-checker, AVpos-generator, AVpos-shifter, Missing-anim-finder, MLP-converter, Noob-detector. Could you help me?

**Comment by Sei-Lisa** [comment]
Glad you got it working! Sorry, you'll have to wait until the rest of scripts are ported to OpenSim. That takes time. Currently only the core scripts are ported.
