### ISSUE TITLE
settings.php notecard size limit

### ISSUE THREAD

**Issue by codeviolet** [AVsitter/AVsitter#49]
I am getting the (very occasional) email error notice from the ```settings.php``` script:

```
ERR03: Data too long for column 'text' at row 1
```

When I look up the entry I note the user is attempting to submit a notecard larger than the [64K limit imposed by MySql type TEXT](https://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html#data-types-storage-reqs-strings). I have manually changed the MySql field type to ```MEDIUMTEXT``` on the server as an interim fix but feel something more is probably wanted in the long run.

Perhaps there should be a ```max_notecard_size``` specified at the top of settings.php and an error notice posted in place of the notecard if it is exceeded, when they visit the link? Currently a user exceeding the limit just receives the "Data was incomplete, please try again." message.

SL has a limitation on notecard size so perhaps this should be the limit accepted by the script, giving a special error message if it is exceeded. 

Or, rerhaps it is enough just to change the field type to ```MEDIUMTEXT```?

**Comment by Sei-Lisa** [comment]
Does the 64K limit apply to OpenSim as well? I don't know, but if not, then it seems clear that we have to support both at the same time. A run-time parameter that only applies to OpenSim would work for this purpose, something like:

```lsl
string url = "https://avsitter.com/settings.php"; // OSS::string url="https://avsitter.com/settings.php?opensim=1"
```

and emit an error message in case the 64K limit is exceeded in SL.

My RL complicated a lot more during this week than I anticipated, but I'll try to submit a PR for this today.

**Comment by Sei-Lisa** [comment]
Well, I've just tested; with Firestorm 5.0.7 the same 64K limit of a notecard applies to Kitely and OSgrid, therefore I don't think we need to do anything else than report an error.
