### ISSUE TITLE
Experience-enabled [AV]object notice

### ISSUE THREAD

**Issue by Sei-Lisa** [AVsitter/AVsitter#5]
Previously I opened this issue to suggest a wording change to the [AV]object script. After further discussion and reconsideration, now I think that its distribution should just not be limited, and that the notice limiting its redistribution should be removed from the MP version.

**Comment by codeviolet** [comment]
My main concern with the distribution of the [AV]object as a full perm script is that as an "experience-enabled" script the experience itself may be abused or re-sold as part of a competing project.

The experience relies on my personal SL account to remain paid and in good standing with LL, which is beyond the source code.

I'm considering setting this script to no-mod in the in-world distribution. I don't think the MPL says that we can't distribute the [AV]object script in no-mod form, provided the source-code is offered somewhere. Am I wrong?

**Comment by raysilent** [comment]
If anyone is concerned whether a particular product is using the real AVsitter or a somehow modded one, how would they now be able to discover that?

**Comment by codeviolet** [comment]
Hi @raysilent Other projects can use the AVsitter code as permitted under the MPL but should not call their project "AVsitter". We have [separate guidelines](/AVsitter/blob/master/TRADEMARK.mediawiki ) that intend to eventually assure users whether they are using AVsitter or a derivative of it. You are welcome to discuss in a separate topic.

**Comment by Sei-Lisa** [comment]
@codeviolet:

I see a couple misunderstandings here.

First, I don't think that downgrading from Premium to Basic affects existing experiences and scripts; you just can't create new experience keys.

I can't tell for sure, but I've asked in a group, and the replies I received matched what I thought.

I also don't know if you can compile any new scripts with the experience you owned while being Premium. If not, then that could indeed be detrimental to future releases in case you stop paying, but not for the currently released scripts.

Second, and most importantly, you can't recompile a script that has a certain experience enabled that you don't own or have permission to use. I've tried to save `[AV]object` and got this message:

```
Unable to upload <UUID> due to the following reason: you are not authorized to create assets for experience <UUID>.
```

It's just logical. If it were otherwise, it would be open season for any griefer getting a full perms script with a certain experience enabled.

With that in mind, I don't see any possible gain in making the script no mod. It's de facto no mod already, unless the AVsitter experience is disabled or changed to a different one, which they can already do by creating their own script from the source.

**Comment by codeviolet** [comment]
@sei-lisa Thanks for those clarifications. Confirming that I will remove the additional text from the object script in the MP distribution (and update the examples), while leaving the script full perm. Will do so after you acknowledge this change is what you'd like me to do. Thanks!

**Comment by Sei-Lisa** [comment]
Yes, and to be clear, I've submitted PR #7 with the proposed change. You may want to wait a day or so for the MP change, as that's the time frame within which I plan to submit a new release.

**Comment by SaraNyn** [comment]
We haven't released the [AV]object script (or any others) just yet....... would it be acceptable to just remove code referencing experience stuff since it performs no function in IW or any other OS based grid then point the difference out in the script notes? Or is commenting it out, as we've already done, acceptable?

**Comment by Sei-Lisa** [comment]
It is acceptable to do any changes provided they comply with the Mozilla Public License (MPL) 2.0 (not to be confused with MLPv2, the Multi Love Pose engine). The experience-specific parts can be commented out or removed, it doesn't really matter. The experience note asking for the script not to be shared should best be removed, as per commit c157fd9.

**Comment by SaraNyn** [comment]
That answers my question..... thank you very much. I am also going to look at it in pure OpenSim

**Comment by Sei-Lisa** [comment]
Since the script has been released in MP, this issue can be closed.
