### ISSUE TITLE
AVprop and AVobject scripts on Virtual Highway Grid

### ISSUE THREAD

**Issue by chocl8soul** [AVsitter/AVsitter#56]
Hi I am receiving syntax errors when creating the AVprop script (553,52) -= llGetObjectDetail syntax error and for the AVobject script I receive (407, 4) syntax error  experience_permissions(key target_id). I've double checked several times and my scripting is below basic. Can someone please help me or give a suggestion? Thank you.

**Comment by Sei-Lisa** [comment]
Any scripts not included in the OpenSim ZIP are not yet supported in OpenSim., sorry.

The only scripts that can be compiled in OpenSim are the ones that end in `.oss` and the rest are not prepared for running in OpenSim yet.

There are plans to migrate the rest of scripts.

**Comment by chocl8soul** [comment]
Ok thank you for clearing that up.

**Comment by Sei-Lisa** [comment]
Incidentally, just a few hours ago I have uploaded a first alpha version of the scripts to issue #57. It would help if you could test them and report back. Please do so in that issue.

https://github.com/AVsitter/AVsitter/pull/57#issuecomment-341545565
