### ISSUE TITLE
Docs update regarding Aeros support

### ISSUE THREAD

**Issue by raysilent** [AVsitter/AVsitter#6]
Not sure where to post this, may be it could be an issue for documentation or FAQ so they contain information regarding Aeros products support. A simple link to [Aeros wiki](https://bitbucket.org/aeros-in-sl/aeros-api/wiki/Home#markdown-header-compatibility-with-avsittertm) may be provided if necessary.

I'm eager to merge the script with the Xcite addon script, since it's now available open source, but since my script is not open source, I can't be sure if it might be a problem.

**Comment by Sei-Lisa** [comment]
Maybe this request is more adequate for https://github.com/AVsitter/avsitter.github.io, which is the documentation repository.

Regarding the second part of your post, the license is quite explicit. You can't include code from the Xcite plugin into your script without making your script open source under the MPL. You can, however, make a trimmed down version of the Xcite addon script that interfaces via link messages with your closed-source script, as long as you distribute the modified Xcite addon as open source under the MPL.

**Comment by Sei-Lisa** [comment]
I'm afraid we can't do much with this. I'm closing it. Feel free to open a new one with a more concrete proposal in the documentation repository, https://github.com/AVsitter/avsitter.github.io
