### ISSUE TITLE
Unable to get [AV]sitA to compile on opensim region

### ISSUE THREAD

**Issue by CindyEvanier** [AVsitter/AVsitter#63]
I have copied the latest opensim release scripts and all compile correctly except [AV]sitA  which gives an error 
 819,99 Error SO103 THE NAME OBJECT_BODY_TYPE_SHAPE does not exist in the current context (928,8)  Error SO103 THE NAME OBJECT_BODY_TYPE_SHAPE does not exist in the current context

Our region is running as OpenSim 0.8.1 Dev  

I hope I have recorded this correctly

**Comment by Sei-Lisa** [comment]
Assuming you've made a typo and the name is `OBJECT_BODY_SHAPE_TYPE` (which determines the shape type of the avatar's current body, i.e. the gender setting), what that error message means is that your sim version does not support reading the gender set in the shape worn by the avatar. That is used by AVsitter for gender selection.

I recommend updating to a newer OpenSim version.

**Comment by CindyEvanier** [comment]
It was a typo sorry.  I will speak to our grid hosting company about an update thank you

**Comment by Sei-Lisa** [comment]
Note that the minimum version supported is 0.8.2 Post_Fixes as deployed in Kitely grid. 0.9.0+ is also supported The core scripts are fully working there, with no apparent misbehaviour (please grab them from https://github.com/AVsitter/AVsitter/files/1439248/AVsitter2-oss.zip for a more complete pack and bug fixes).
