### ISSUE TITLE
Multiple scripts in description of prim

### ISSUE THREAD

**Issue by JadeJewell** [AVsitter/AVsitter#66]
My partner and I are starting to create furniture and are using avsitter2. We are also using Black Tulip texture change scripts, and we are wanting to use set # and sit targets to do multiple people and the goal is to use other scripts needing to use the description of a prim. Is this possible?

Also, when adding a third person to a set of animations (i.e. mmf/ffm), how would one sync the pose for all three positions?

**Comment by Sei-Lisa** [comment]
Thanks, I'll look into that.

**Comment by Sei-Lisa** [comment]
It should work out of the box if you don't use -1, by placing the seat assignment after a `#`.

However, using -1 to explicitly exclude prims from seat assignment won't work.

**Comment by Sei-Lisa** [comment]
Pull request #68 addresses this.

**Comment by JadeJewell** [comment]
in the description of the prims on the bed, for instance, the blanket, says 0-0#t;bed. it seems to be working in that order, as we have added extra poses/animation. should it be different?

**Comment by Sei-Lisa** [comment]
My understanding is that you would not notice any difference if you used t;bed instead.

For it to work as designed, the seat assignment must be last.

**Comment by JadeJewell** [comment]
ok so i should change it to t;bed#0-0 in the description for each prim (changing the sitter #, 0-1,0-2,0-3). ty sei-lisa

**Comment by Sei-Lisa** [comment]
That's right. Also, if you need to use -1 to skip a prim, you will have to wait for the next release, because that's what was added in my pull request.
