### ISSUE TITLE
reset & texture buttons in adjust menu?

### ISSUE THREAD

**Issue by JadeJewell** [AVsitter/AVsitter#72]
question, is it possible to use both a reset button/script and a texture button/script on the adjust menu? this is at the top of the avpos notecard:

◆ADJUST [RESET]|99
◆ADJUST [Texture]|-1864098

when we have that in now, it just shows the first listed, ie reset. how do we get both to show in the adjust menu?

**Comment by AurynBeorn** [comment]
The [ADJUST button documentation](https://avsitter.github.io/avsitter2_avpos.html#adjust) explains how to add more than one button when using it. In your case, it would look like this:

    ADJUST [RESET]|99|[Texture]|-1864098

I hope this helps!

**Comment by JadeJewell** [comment]
tyvm auryn! i thought i had saw it somewhere but when i was looking at the site, somehow i overlooked that lol
