### ISSUE TITLE
[AV]prop attachment orientation problem

### ISSUE THREAD

**Issue by dale59911** [AVsitter/AVsitter#74]
I have having an issue with the latest OpenSim version.  When using a prop with an animated pose, the prop attaches to the correct point but not in the saved rotated.  When I attach this prop directly from my inventory, it attaches correctly, ie the correct point and the saved orientation.  I know that second life and I assume the OpenSim is the repository for orientation of attached objects.  When I use the SL version, in SL, everything works correctly so I don't think I am doing anything procedurally incorrect.  Please let me know what relevant information you need.

**Comment by Sei-Lisa** [comment]
I can reproduce this problem. When any script (AVprop in this case) rezzes the prop, the attachment position is preserved, but the rotation is lost. This is an OpenSim problem. I suggest you file it with OpenSim. http://opensimulator.org/mantis/

Easily reproducible like this:

- Create a prim. I used a torus.
- Attach it to your hand.
- Adjust it so it looks like a bracelet. This requires a 90° rotation and some movement.
- Take it, and put it inside another object.
- Put the following script inside: `default{touch_start(integer n){llRezObject(llGetInventoryName(0),llGetPos()+<0,0,1>,<0,0,0>,<0,0,0,1>,1);}}`
- Touch the object. The torus will be rezzed.
- Take the new torus.
- Attach it. Observe the position is right, but the rotation is wrong.
- Take the torus from the object inventory and attach it. Observe the position and the rotation are both right.

**Comment by Sei-Lisa** [comment]
As a workaround, you can include a script like this:
```lsl
default
{
    attach(key id)
    {
        if (id) llSetLocalRot(llEuler2Rot(DEG_TO_RAD*<10,20,30>));
    }
}
```

but changing `<10,20,30>` to the rotation of the attachment.

Note: I've edited the previous post to fix a mistake I made in the script, to make the steps more accurate, and to add extra information.

**Comment by dale59911** [comment]
Thank you for taking a look at this.  I will file this with OpenSim.  Do you mind if I include you analysis when I do so?

**Comment by Sei-Lisa** [comment]
No problem, feel free to include my (revised) analysis.

**Comment by dale59911** [comment]
Hello Sei-Lisa,

You may remember this problem having to do with a an object rezzed by a script and having the correct attachment but an improper orientation.  This OpenSim glitch is really causing me some problems.  I am not a scripter but would love to get this work around in place.  Would this script be placed in the content folder of the object I am trying to rezz with avsitter?  I apologize if this is a stupid question, and I am pretty confident that it is just that.  

Thanks for all your help on this….The person that set up our grid in OpenSim is sending this through the OpenSim help desk in an effort to get this corrected.

Regards,

Dale Roach
 
I apologize if you get this email twice.  I thought I sent it yesterday but saw it in my draft folder and it was not in my sent folder………The joys being 70  LOL

**Comment by Sei-Lisa** [comment]
> Would this script be placed in the content folder of the object I am trying to rezz with avsitter?

Yes, that's it. The script sets a new rotation immediately after attach, so that it overrides the default rotation. Remember that for it to work, you need to enter the rotation of the attachment in place of <10,20,30>.

> Thanks for all your help on this….The person that set up our grid in OpenSim is sending this through the OpenSim help desk in an effort to get this corrected. 

I'd appreciate a link to the issue in case it's public. I've been monitoring the OpenSim Mantis bug tracker http://opensimulator.org/mantis/my_view_page.php but nothing showed up.

**Comment by dale59911** [comment]
I will give it a try..thank you so much.  You are a lifesaver!!!

Regards,

Dale

**Comment by dale59911** [comment]
THANK YOU THANK YOU THANK YOU…It worked beautifully.  

Many Regards……

Dale

**Comment by Sei-Lisa** [comment]
I've reported this myself as Mantis bug 8364.

http://opensimulator.org/mantis/view.php?id=8364

Note the workaround script in this thread was wrong, causing errors sometimes when the props are detached. I've updated it and now it shouldn't give errors.

**Comment by typhartez** [comment]
I know this issue has been closed a long time ago, but as nothing moves on OpenSim side, I made [a project](https://github.com/typhartez/avsitter-plugin-osprop) to provide a workaround. That could help someone needing a solution.
