### ISSUE TITLE
question about different sitters/menus

### ISSUE THREAD

**Issue by JadeJewell** [AVsitter/AVsitter#76]
we are currently working on a project of a dance pole, and 4 chairs surrounding. we are wanting to make the dance pole interact with each chair, as well as add menus in each chair for cuddles/sex/lapdances. can someone direct me on how this would be possible?

i am thinking, avsitter scripts/animations in dance pole for seperate menu, but also have it sync with animations in each chair, and do the same with the chairs as if they are separate projects. would this be the correct way?

**Comment by JadeJewell** [comment]
another question, as far as the entertainer on the pole, how would it be possible for that sitter to have control of the menu and then pass the menu to one of the sitters at an appropriate time, as in not have access to the menu until "given" permission to access the menu?

**Comment by Sei-Lisa** [comment]
Hello, this issue tracker is for reporting problems with AVsitter itself, not for support with specific usages.

Please see the support options in https://avsitter.github.io/support.html

Thanks.
