### ISSUE TITLE
Its a project for script make a buttons in adjust menu

### ISSUE THREAD

**Issue by LuckyBrasil** [AVsitter/AVsitter#81]
i have a project for sounds for pose... and i like a script or the link message(codig) for avsitter understand and make news buttons in ajust menu, configurad in my script...

like 
in menu adjust add  "BUTTON SOUND ON"
in menu adjust add "BUTTON SOUND OFF" ..
i know it i can make in notecard avpos .. but i cant work with script .. its possible?

thanks!

**Comment by Sei-Lisa** [comment]
This is not an AVsitter bug, so I suggest you use the support options listed in https://avsitter.github.io/support.html for help.
