### ISSUE TITLE
em Props script menu - dialog pages 

### ISSUE THREAD

**Issue by LuckyBrasil** [AVsitter/AVsitter#85]
in menu for props the dialog pages button, if have more 1 page, only return a page 1 if i choice a button in page 2 and click return only a page 1

**Comment by Sei-Lisa** [comment]
Are you using [AV]menu? Can you give an example AVpos notecard that shows the problem?

**Comment by LuckyBrasil** [comment]
yes in [AV] Menu

◆BUTTON Apple Pie
◆BUTTON Brazil Salad
◆BUTTON Breakfast
◆BUTTON Chinese Food
◆BUTTON Christmas Snack
◆BUTTON Cupcake
◆BUTTON Dinner
◆BUTTON Fish
◆BUTTON Fruits
◆BUTTON Hamburger
◆BUTTON Muffin
◆BUTTON Oliveir Salad
◆BUTTON Paella
◆BUTTON Pancakes
◆BUTTON Pasta
◆BUTTON Russian Salad
◆BUTTON Salad
◆BUTTON Soup
◆BUTTON Spaghetti
◆BUTTON Steak

◆PROP Apple Pie|.:LD:. Apple pie:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Brazil Salad|.:LD:. Brazil Salad:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Breakfast|.:LD:. Breakfast:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Chinese Food|.:LD:. Chinese Food:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Christmas Snack|.:LD:. Christmas Snack:.|G1|<-0.00026, -0.01515, 0.22559>|<0.00000, 0.00000, 0.00000>|
◆PROP Cupcake|.:LD:. Cupcake:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Dinner|.:LD:. Dinner:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Fish|.:LD:. Fish:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Fruits|.:LD:. Fruits:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Hamburger|.:LD:. Hamburger:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Muffin|.:LD:. Muffin:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Oliveir Salad|.:LD:. Oliveir Salada:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Paella|.:LD:. Paella:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Pancakes|.:LD:. Pancakes:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Pasta|.:LD:. Pasta:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Russian Salad|.:LD:. Russian Salad:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Salad|.:LD:. Salad:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Soup|.:LD:. Soup:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Spaghetti|.:LD:. Spaghetti:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|
◆PROP Steak|.:LD:. Steak:.|G1|<-0.000264, -0.015150, 0.332275>|<0.000000, 0.000000, 0.000000>|

**Comment by Sei-Lisa** [comment]
OK, thanks for your input. This is another instance of issue #77. There's a fix being worked on.
