### ISSUE TITLE
Question! 2 prims 2 menus

### ISSUE THREAD

**Issue by LuckyBrasil** [AVsitter/AVsitter#89]
Hello, I am trying to do, 2 linked prims, with separate menus and separate poses, which I would like to know, if possible, sit on the prim 1 and be able to call the menu that is in the prim 2 because I have no memory in one only script, there are many poses, so I thought I'd split, but I do not know if it's possible, call the script in prim2, through the script menu in prim1, and vice versa!
Thank you!

**Comment by Sei-Lisa** [comment]
I don't think this is possible, but I suggest you use the support options listed in https://avsitter.github.io/support.html instead of this bug tracker, as you can probably obtain more meaningful answers that way.
