### ISSUE TITLE
AVsitter 2 InWorldz

### ISSUE THREAD

**Issue by SaraNyn** [AVsitter/AVsitter#9]
This likely needs to be moved ..... if so please advise as to where.
I have imported AVsitter 2 to InWorldz. Everything functions fine though we did have to comment out the experience section as InWorldz does not support that. 
The resulting work will be available at The Free Script Library following the terms of the MLP.  
It's worth noting scripting in InWorldz  is more  SL compatible than other OpenSim based grids so your mileage may vary.

**Comment by Sei-Lisa** [comment]
Hi SaraNyn - Thanks for letting us know. It would be nice if we can see the actual changes to the code, and for that purpose it would be best to see it in the form of a pull request or at least a commit in a public repository. Would that be possible?

**Comment by SaraNyn** [comment]
[[AV}object(IW).zip](https://github.com/AVsitter/AVsitter/files/1207023/AV.object.IW.zip)

**Comment by Sei-Lisa** [comment]
Thank you for posting the `[AV]object` code. We'd be interested in the whole set, though. Is it possible to post it here?

**Comment by SaraNyn** [comment]
[AVsitter 2.2.zip](https://github.com/AVsitter/AVsitter/files/1207822/AVsitter.2.2.zip)

 As I mentioned this will be distributed at The Free Script Library in InWorldz. I am in no way affiliated with TFSL aside from contributing this code which is her in it's entirety and being a a normal member of the group which is required to access scripts

**Comment by Sei-Lisa** [comment]
Thank you very much. I see no changes to the code apart from the experience bits and some symbols replaced by question marks; does that mean it's a verbatim copy of the scripts, and that it worked out of the box? If so, that speaks quite well of the Halcyon engine's compatibility.

The problem is that we need to make it work on the OpenSim engine, which seems to be way behind Halcyion compatibility wise. I believe we have achieved that, though it needs more testing now; see #8.

**Comment by SaraNyn** [comment]
If I can help (with opensim) I'd be happy too. I also know a fantastic opensim scripter, but she's very busy ....... So much so I doubt me asking would have much if any impact whether she would assist or not. The scripts are in fact copied verbatim. I *would* very much like to know where those symbols are located in the scripts so I could put them right in IW...... I have workarounds....but I'd like for things to be perfect.. Finally ....I was stunned to import that much stuff with only *one* error....the experience matter.

**Comment by Sei-Lisa** [comment]
The OpenSim version is being worked on. I don't think there's much reason to keep this open. Thanks for the report and the modified script.
