### ISSUE TITLE
BUTTON no longer sending correct llMessageLinked

### ISSUE THREAD

**Issue by RiderDavis** [AVsitter/AVsitter#95]
I noticed a funny problem I thought I'd mention... Maybe help someone from wasting as much time as I had before I'd realized what was going on...

I've noticed I'm getting strange linked message results since commit bf8f10b to the AVpos B script located here; https://github.com/AVsitter/AVsitter/commit/bf8f10bfe6999a8aa7aaef5cecb977ec616896f7#diff-b372a0846c752c0744b22a8678bfb2f7

To be specific, adding `BUTTON mybuttonname|666` doesn't actually create the intended linked message of `llMessageLinked(X, 666, mybuttonname, MenuUserUUID);` instead it is now only sending `llMessageLinked(X, 90101, 666|mybuttonname|MenuUserUUID, MenuUserUUID);`

Merely using the version of the AVpos B script prior to this adjustment resolves the problem, though I've not had the availability to dig into it further but I thought if I was having this problem with a _fresh copy_ of the scripts other people might be too without even realizing it.

Hope someone might find this interesting!

~Rider

**Comment by Sei-Lisa** [comment]
Thanks for your report. I've tried to reproduce it in SL but I was unsuccessful; for me, the only message generated by such a BUTTON line is 666 and not 90101.

Can you give more details about your setup and the grid you're running it in?

**Comment by Sei-Lisa** [comment]
Never mind that. I can reproduce it with current master, but not with any released version (all released versions include commit bf8f10b which is not the culprit).

The culprit is actually a65d7cd. I will investigate, thanks for the report!

**Comment by RiderDavis** [comment]
Awesome! Great to hear you were able to catch it easily, and entirely my pleasure! _**Cheers!**_
