### ISSUE TITLE
RLV/Lockguard script issue

### ISSUE THREAD

**Issue by JadeJewell** [AVsitter/AVsitter#97]
my partner and i are working on a bed wanting to use RLV in a bdsm menu. we have the rings linked to the bed (4 rings, named ring1, ring2, ring3, ring4), inside the lockguard script we have 

list POSES = [
        "Feed Her", "leftwrist,ring2,rightwrist,ring1,leftankle,ring4,rightankle,ring3",
        "Cunt Probe", "leftwrist,ring2,rightwrist,ring1,leftankle,ring4,rightankle,ring3",
        "Chained Melody", "leftwrist,ring2,rightwrist,ring1,leftankle,ring4,rightankle,ring3",
        "Hard Thrust", "leftwrist,ring2,rightwrist,ring1,leftankle,ring4,rightankle,ring3"

those for 4 of the first poses in the bdsm bed menu, but the chains actually show up from my cuffs while in the poses, but they are all 4 going to ring2, which was designated for the leftwrist cuff.

is there another script or notecard we should be adding to the root prim? do i need to make a copy of my cuffs and rename them to match what's listed in the script (ie rightwrist,leftwrist, etc) so they will go to the appropriate ring?

**Comment by Sei-Lisa** [comment]
Hello, this issue tracker is for reporting problems with AVsitter itself, not for support with specific usages.

Please check the support options in https://avsitter.github.io/support.html

Thanks.
